name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Deno Install
        run: |
          deno install --frozen

      - name: Lint
        run: |
          deno lint

      - name: Check Formatting
        run: |
          deno fmt --check

      - name: Type Check
        run: |
          deno check

      - name: Publish Dry Run
        run: |
          deno publish --dry-run

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Deno Install
        run: |
          deno install --frozen

      - name: Prepare Tests
        run: |
          deno task playwright install --with-deps chromium

      - name: Test
        run: |
          deno task test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results
          path: test-results/
