name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Lint
        run: |
          deno lint

      - name: Check Formatting
        run: |
          deno fmt --check

      - name: Type Check
        run: |
          deno check

      - name: Publish Dry Run
        run: |
          deno publish --dry-run
